<%
'--------------------------------------------------------------------
' Archivo MetaData META.INC
'
'--------------------------------------------------------------------
%>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Expires" content="0" />
<meta http-equiv="Last-Modified" content="0" />
<meta http-equiv="Cache-Control" content="no-cache, mustrevalidate" />
<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="Cache-Control" content="no-store" />
<meta http-equiv="Pragma" content="no-cache" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
<meta property="og:title" content="Sistema WorkFlow V3" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://www.wf.segegob.gob.cl" />
<meta property="og:image" content="http://www.wf.segegob.gob.cl/img/logo_mintrab.png" />
<meta property="og:site_name" content="WorkFlowV3" />
<meta property="og:description" content="Sistema WorkFlow V3" />

<link rel="icon" href="img/favicon.ico">
